spring:
  application:
    name: we-work
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:file:./new-parquimetro-prd
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    operationsSorter: method

api:
  security:
    token:
      secret: my-secret